# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Beeptalk"
client_id = "5a032558694adc8a81f435ea89c01a21"
application_url = "https://disco-popularity-obesity-conclusion.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://disco-popularity-obesity-conclusion.trycloudflare.com/auth/callback",
  "https://disco-popularity-obesity-conclusion.trycloudflare.com/auth/shopify/callback",
  "https://disco-popularity-obesity-conclusion.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-338352a4.myshopify.com"
